name: Get Citation Data

on: 
  schedule:
    - cron: '0 0 * * *'   # Daily at midnight UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      Email: ${{ vars.EMAIL }}
      GOOGLE_SCHOLAR_ID: ${{ secrets.GOOGLE_SCHOLAR_ID }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r google_scholar_crawler/requirements.txt

    - name: Debug Environment
      run: echo "Scholar ID is set to ${GOOGLE_SCHOLAR_ID}"

    - name: Run Crawler Script
      run: |
        echo "[INFO] Running crawler script..."
        cd google_scholar_crawler
        timeout 60s python3 main.py || echo "[ERROR] Script timed out"
    
    - name: Push Result Files
      run: |
        cd google_scholar_crawler/results
        git init
        git config --local user.email "${Email}"
        git config --local user.name "${GITHUB_ACTOR}"
        git add *.json
        git commit -m "Update Scholar Data [auto]"
        git branch -M google-scholar-stats
        git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        git push origin google-scholar-stats --force
